BEGIN TRANSACTION;
INSERT INTO "game" VALUES (1,'Game 1','2022-11-27',NULL);
INSERT INTO "game_player_nation" VALUES (1,1,1,NULL,81,NULL);
INSERT INTO "nation" VALUES (1,'Minoa',1);
INSERT INTO "nation" VALUES (2,'Assyria',3);
INSERT INTO "nation" VALUES (3,'Celts',5);
INSERT INTO "nation" VALUES (4,'Carthage',7);
INSERT INTO "nation" VALUES (5,'Hatti',9);
INSERT INTO "nation" VALUES (6,'Rome',11);
INSERT INTO "nation" VALUES (7,'Iberia',13);
INSERT INTO "nation" VALUES (8,'Hellas',15);
INSERT INTO "nation" VALUES (9,'Egypt',17);
INSERT INTO "player" VALUES (1,'Rob McArthur','Rob M.','RobOfTheNorth');
INSERT INTO "player" VALUES (2,'Allister','Allister',NULL);
INSERT INTO "player" VALUES (3,'Chris','Chris',NULL);
INSERT INTO "player" VALUES (4,'Don','Don',NULL);
INSERT INTO "player" VALUES (5,'Lucas','Lucas',NULL);
INSERT INTO "player" VALUES (6,'Morry','Morry',NULL);
INSERT INTO "player" VALUES (7,'Sandy','Sandy',NULL);
COMMIT;
